# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="croptopia" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory
displayName="Croptopia" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="croptopia-forge.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Thonk, Rainbowcraft2" #optional
description='''
Crop mod for forge
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.croptopia]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[37,)" #mandatory
   ordering="NONE"
   side="BOTH"
# Here's another dependency
[[dependencies.croptopia]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.17.1,)"
   ordering="NONE"
   side="BOTH"
